### PR TITLE
fix type

### PR DESCRIPTION
**Pull request by kaichaosun**

### CODE REVIEW

**Review by GopherJ — APPROVED** [review]

**Comment by GopherJ** [comment]
is it possible to have subscan?

**Review by yz89 — APPROVED** [review]

**Comment by GopherJ** [comment]
I tried to apply this change on the server, then I tried to request the faucet but got:
image
do you have an idea on this?

**Comment by kaichaosun** [comment]
LookupSource is not in your types.json? @GopherJ

**Comment by kaichaosun** [comment]
Let's request subscan to add us after have a public testnet.

**Pull request merged**
